<GameOverScreen>:
    canvas.before:
        Color:
            rgb: (0, 0, 0, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
    MDFloatLayout:
        Image:
            id: health_hud
            source: 'assets/image/hp/health-hud-10.png'
            size_hint: 0.19, 0.08
            opacity: 1
            pos_hint: {'center_x': 0.1,'center_y': 0.95}
            fit_mode: 'fill'
        Image:
            id: coin_hud
            source: 'assets/image/coin-hud.png'
            size_hint: 0.19, 0.08
            opacity: 1
            pos_hint: {'center_x': 0.1,'center_y': 0.85}
            fit_mode: 'fill'
        Label:
            id: coin_label
            text: str(root.coins)
            font_size: self.height * 1.2
            font_name: 'assets/fonts/PixelifySans-Regular.ttf'
            color: (1, 0.718, 0.149, 1)
            size_hint: 0.145, 0.065
            opacity: 1
            pos_hint: {'center_x': 0.118, 'center_y': 0.85}
        Label:
            id: dialog_label
            text: ''
            font_size: self.height * 0.2
            halign: 'center'
            font_name: 'assets/fonts/PixelifySans-Regular.ttf'
            color: (1, 1, 1, 1)
            size_hint: 0.2, 0.4
            opacity: 0
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    Widget:
        id: end_white_screen
        size_hint: 1, 1
        opacity: 0
        canvas:
            Color:
                rgba: (1, 1, 1, self.opacity)
            Rectangle:
                pos: self.pos
                size: self.size