<GameScreen>:
    canvas.before:
        Color:
            rgb: (0.051, 0.059, 0.169, 1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
    MDFloatLayout:
        MDFloatLayout:
            id: bullets
        Image:
            id: space_ship
            source: 'assets/image/ship/space-ship-idle_apng.png'
            size_hint: 0.15, 0.15
            pos: root.ship_x, root.ship_y
            fit_mode: 'fill'
        Image:
            id: health_hud
            source: 'assets/image/hp/health-hud-10.png'
            size_hint: 0.19, 0.08
            pos_hint: {'center_x': 0.1,'center_y': 0.95}
            fit_mode: 'fill'
        Image:
            id: coin_hud
            source: 'assets/image/coin-hud.png'
            size_hint: 0.19, 0.08
            pos_hint: {'center_x': 0.1,'center_y': 0.85}
            fit_mode: 'fill'
        Label:
            text: str(root.coins)
            font_size: self.height * 1.2
            font_name: 'assets/fonts/PixelifySans-Regular.ttf'
            color: (1, 0.718, 0.149, 1)
            size_hint: 0.145, 0.065
            pos_hint: {'center_x': 0.118, 'center_y': 0.85}

    MDFloatLayout:
        Button:
            id: pause
            background_normal: 'assets/image/buttons/button-paused.png'
            background_down: 'assets/image/buttons/button-paused.png'
            border: 0, 0, 0, 0
            size_hint: None, None
            size_hint: 0.045, 0.11
            pos_hint: {'center_x': 0.97, 'center_y':0.93}
            on_press: root.show_pause(); app.game_music.stop()

        Button:
            id: move_left
            background_normal: 'assets/image/buttons/button-left.png'
            background_down: 'assets/image/buttons/button-left.png'
            border: 0, 0, 0, 0
            size_hint: None, None
            size_hint: 0.045, 0.11
            pos_hint: {'center_x': 0.03, 'center_y':0.165}
            on_press: root.pressKey('left')
            on_release: root.releaseKey('left')
        Button:
            id: move_down
            background_normal: 'assets/image/buttons/button-down.png'
            background_down: 'assets/image/buttons/button-down.png'
            border: 0, 0, 0, 0
            size_hint: None, None
            size_hint: 0.045, 0.11
            pos_hint: {'center_x': 0.075}
            on_press: root.pressKey('down')
            on_release: root.releaseKey('down')
        Button:
            id: move_up
            background_normal: 'assets/image/buttons/button-up.png'
            background_down: 'assets/image/buttons/button-up.png'
            border: 0, 0, 0, 0
            size_hint: None, None
            size_hint: 0.045, 0.11
            pos_hint: {'center_x': 0.075, 'center_y': 0.27}
            on_press: root.pressKey('up')
            on_release: root.releaseKey('up')
        Button:
            id: move_right
            background_normal: 'assets/image/buttons/button-right.png'
            background_down: 'assets/image/buttons/button-right.png'
            border: 0, 0, 0, 0
            size_hint: None, None
            size_hint: 0.045, 0.11
            pos_hint: {'center_x': 0.12, 'center_y':0.165}
            on_press: root.pressKey('right')
            on_release: root.releaseKey('right')

        Button:
            id: shot
            background_normal: 'assets/image/buttons/button-shot.png'
            background_down: 'assets/image/buttons/button-shot.png'
            border: 0, 0, 0, 0
            size_hint: None, None
            size_hint: 0.045, 0.11
            pos_hint: {'center_x': 0.88, 'center_y':0.165}
            on_press: root.pressKey('shot')
            on_release: root.releaseKey('shot')
    
    Button:
        id: blocker_game
        size_hint: 0, 0
        background_color: (0, 0, 0, 1)
        opacity: 0
        disabled: True

    MDCard:
        id: pause_panel
        size_hint: 0, 0
        opacity: 0
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        md_bg_color:( 0, 0, 0, 0)
        radius: [0, 0, 0, 0]
        orientation: 'vertical'
        spacing: self.width * 0.01
        padding: self.width * 0.01
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Rectangle:
                source: 'assets/image/buttons/button-bg-big.png'
                pos: self.pos
                size: self.size

        MDLabel:
            text: 'Pause'
            bold: True
            halign: 'center'
            color: (1, 1, 1, 1)
            font_size: self.height * 0.2
            font_name: 'assets/fonts/PressStart2P-Regular.ttf'
            size_hint: 0.25, 0.3
            pos_hint: {'center_x': 0.5,'center_y': 0.95}


        MDBoxLayout:
            orientation: 'vertical'
            spacing: self.width * 0.03
            padding: self.width * 0.01
            Button:
                text: 'Continue'
                background_normal: 'assets/image/buttons/button-bg.png'
                background_down: 'assets/image/buttons/button-bg.png'
                bold:True
                color: (1, 1, 1, 1)
                halign: 'left'
                valign: 'middle'
                font_size: self.height * 0.2
                font_name: 'assets/fonts/PressStart2P-Regular.ttf'
                on_press: root.hide_pause(); app.game_music.play() if app.music_enabled == True else None
            Button:
                text: 'Return to menu'
                background_normal: 'assets/image/buttons/button-bg.png'
                background_down: 'assets/image/buttons/button-bg.png'
                bold:True
                color: (1, 1, 1, 1)
                halign: 'left'
                valign: 'middle'
                font_size: self.height * 0.2
                font_name: 'assets/fonts/PressStart2P-Regular.ttf'
                on_press: app.save_game(); app.go_to_menu();
            Button:
                text: 'Exit the game'
                background_normal: 'assets/image/buttons/button-bg.png'
                background_down: 'assets/image/buttons/button-bg.png'
                bold:True
                color: (1, 1, 1, 1)
                halign: 'left'
                valign: 'middle'
                font_size: self.height * 0.2
                font_name: 'assets/fonts/PressStart2P-Regular.ttf'
                on_press: app.save_game(); app.quit()

    Widget:
        canvas:
            Color:
                rgba: 0, 0, 0, app.brightness
            Rectangle:
                pos: self.pos
                size: self.size

<Shot@Image>:
    id: shot
    source: 'assets/image/shot.png'
    size_hint: None, None
    size: 20, 20